version: "3"
services:
  app:
    build: .
    command: make test
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./config/:/go/src/app/config/
      - ./test/:/go/src/app/test/
      - ./examples/:/go/src/app/examples/
      - ./Makefile:/go/src/app/Makefile

